### ISSUE TITLE
RuntimeError: "sum_cpu" not implemented for 'Bool'

### ISSUE THREAD

**Issue by YongZh131** [marble0117/gcnns#1]
Traceback (most recent call last):
  File "D:/z_study/code/gcnns-master/main.py", line 21, in <module>
    trainer.run()
  File "D:\z_study\code\gcnns-master\train.py", line 136, in run
    evals = self.evaluate()
  File "D:\z_study\code\gcnns-master\train.py", line 112, in evaluate
    acc = pred.eq(data.labels[mask]).sum().item() / mask.sum().item()
RuntimeError: "sum_cpu" not implemented for 'Bool'

Process finished with exit code 1

When I run the code, I get the above error.

**Comment by marblet** [comment]
I am not sure but this might be a problem for the version of PyTorch.
I use PyTorch 1.3 and 1.4 with Python 3.6 on my environment.
Could you make new environment like me and try to run the code?

**Comment by YongZh131** [comment]
> I am not sure but this might be a problem for the version of PyTorch.
> I use PyTorch 1.3 and 1.4 with Python 3.6 on my environment.
> Could you make new environment like me and try to run the code?

I have solved it, thank you.
